import Head from "next/head";
import BlogSection from "../components/Home/BlogSection";
import { CarSelection } from "../components/Home/CarSelection";
import Featured from "../components/Home/Featured/index";
import Hero from "../components/Home/Hero";
import SellYourCar from "../components/Home/SellYourCar";
import WhyChooseUs from "../components/Home/WhyChooseUs";
import DefaultLayout from "../components/layouts/DefaultLayout";


const Home = () => {
  // useEffect(() => {
  //   const makes = ["toyota", "bmw"];
  //   const models = ["corolla", "camry", "x5", "x6"];
  //   dispatch(getCars({ makes, models }));
  // }, []);

  return (
    <DefaultLayout>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className="bg-pageBg">
        <Hero />
        <WhyChooseUs />
        <Featured />
        <CarSelection />
        <SellYourCar />
        <BlogSection />
      </main>
    </DefaultLayout>
  );
};

// Home.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;

// Home.displayName = "Home";

export default Home;

