import Head from "next/head";
import { useEffect } from "react";
import BlogSection from "../components/Home/BlogSection";
import { CarSelection } from "../components/Home/CarSelection";
import Featured from "../components/Home/Featured/index";
import Hero from "../components/Home/Hero";
import SellYourCar from "../components/Home/SellYourCar";
import WhyChooseUs from "../components/Home/WhyChooseUs";
import DefaultLayout from "../components/layouts/DefaultLayout";
import { getCars } from "../features/car/carSlice";
import { useAppDispatch } from "../store/hooks";

const Home = () => {
  const dispatch = useAppDispatch();
  // useEffect(() => {
  //   const makes = ["toyota", "bmw"];
  //   const models = ["corolla", "camry", "x5", "x6"];
  //   dispatch(getCars({ makes, models }));
  // }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-NWKN60DN2D"
        ></script>

        <script
          dangerouslySetInnerHTML={{
            __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag() {
              dataLayer.push(arguments);
            }
            gtag("js", new Date());
            gtag("config", "G-NWKN60DN2D");
          `,
          }}
        />
      </Head>

      <main className="bg-pageBg">
        <Hero />
        <WhyChooseUs />
        <Featured />
        <CarSelection />
        <SellYourCar />
        <BlogSection />
      </main>
    </>
  );
};

Home.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;

export default Home;
