import Head from "next/head";
import BlogSection from "../components/Home/BlogSection";
import { CarSelection } from "../components/Home/CarSelection";
import Featured from "../components/Home/Featured";
import Hero from "../components/Home/Hero";
import SelllYourCar from "../components/Home/SelllYourCar";
import WhyChooseUs from "../components/Home/WhyChooseUs";
import DefaultLayout from "../components/layouts/DefaultLayout";


const Home = () => {
  // useEffect(() => {
  //   const makes = ["toyota", "bmw"];
  //   const models = ["corolla", "camry", "x5", "x6"];
  //   dispatch(getCars({ makes, models }));
  // }, []);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-pageBg">
        <Hero />
        <WhyChooseUs />
        <Featured />
        <CarSelection />
        <SelllYourCar />
        <BlogSection />
      </main>
    </>
  );
};

Home.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;

export default Home;

{
  /* <ThreeSixty
          amount={36}
          imagePath={threeSSixtyPanoramaImage}
          fileName="chair_{index}.jpg?v1"
        /> */
}

// const Panellum360 = () => {
//   const [yaw, setYaw] = useState(0);
//   const [pitch, setPitch] = useState(0);
//   const panImage: any = useRef(null);
//   return (
//     <>
//       <div> Pitch: {pitch} </div>
//       <div> Yaw: {yaw} </div>
//       <Pannellum
//         width="100%"
//         height="500px"
//         image="https://i2.wp.com/www.samrohn.com/wp-content/uploads/le-meridien-bedroom-panorama.jpg?resize=1200%2C600"
//         pitch={10}
//         yaw={180}
//         hfov={110}
//         autoLoad
//         showZoomCtrl={false}
//         onMouseup={(event: any) => {
//           setPitch(panImage.current.getViewer().mouseEventToCoords(event)[0]);
//           setYaw(panImage.current.getViewer().mouseEventToCoords(event)[1]);
//         }}
//       >
//         <Pannellum.Hotspot
//           type="custom"
//           pitch={12.41}
//           yaw={117.76}
//           handleClick={(evt: any, name: any) => console.log(name)}
//           name="image info"
//         />
//       </Pannellum>
//     </>
//   );
// };
