import Head from "next/head";
import { useRouter } from "next/router";
import React, { useEffect } from "react";
import FeaturesSpecs from "../../components/CarDetails/FeaturesSpecs";
import CarSummary from "../../components/CarDetails/CarSummary";
import ExtraLinks from "../../components/CarDetails/ExtraLinks";
import GalleryNavigation from "../../components/CarDetails/Gallery/GalleryNavigation";
import HistoryInspection from "../../components/CarDetails/HistoryInspection";
import RatingsReview from "../../components/CarDetails/RatingsReview";
import RecommendedCars from "../../components/CarDetails/RecommendedCars/RecommendedCars";
import TopDetails from "../../components/CarDetails/TopDetails";
import DefaultLayout from "../../components/layouts/DefaultLayout";
import { getCar } from "../../features/car/carSlice";
import { useAppDispatch, useAppSelector } from "../../store/hooks";
import Gallery from "../../components/CarDetails/Gallery/Gallery";
import ExteriorThreeSixty from "../../components/CarDetails/Gallery/ExteriorThreeSixty";
import InteriorThreeSixty from "../../components/CarDetails/Gallery/InteriorThreeSixty";

const CarDetails = () => {
  const dispatch = useAppDispatch();
  const router = useRouter();
  const { id } = router.query as { id: string };

  const { carDetailsActiveTab } = useAppSelector((state) => state.ui);

  useEffect(() => {
    if (!router.isReady) return;
    dispatch(getCar(id));
  }, [dispatch, router, id]);

  return (
    <div className="font-roboto">
      <Head>
        <title>Car Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {carDetailsActiveTab === 0 ? (
        <div>
          <TopDetails />
          <GalleryNavigation />
          <CarSummary />
          <FeaturesSpecs />
          <HistoryInspection />
          <RecommendedCars />
          <RatingsReview />
          <ExtraLinks />
        </div>
      ) : carDetailsActiveTab === 1 ? (
        <Gallery />
      ) : carDetailsActiveTab === 2 ? (
        <ExteriorThreeSixty />
      ) : carDetailsActiveTab === 3 ? (
        <InteriorThreeSixty />
      ) : null}
    </div>
  );
};

CarDetails.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;

export default CarDetails;
