import Head from "next/head";
import React from "react";
import CarSpecs from "../../components/CarDetails/CarSpecs";
import ExtraLinks from "../../components/CarDetails/ExtraLinks";
import Gallery from "../../components/CarDetails/Gallery";
import HistoryInspection from "../../components/CarDetails/HistoryInspection";
import RatingsReview from "../../components/CarDetails/RatingsReview";
import RecommendedCars from "../../components/CarDetails/RecommendedCars/RecommendedCars";
import TopDetails from "../../components/CarDetails/TopDetails";
import DefaultLayout from "../../components/layouts/DefaultLayout";
import { LeftArrowIcon } from "../../components/ui/icons";

const CarDetails = () => {
  return (
    <div className="font-roboto">
      <Head>
        <title>Car Details</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <TopDetails />
      <Gallery />
      <CarSpecs />
      <HistoryInspection />
      <RecommendedCars />
      <RatingsReview />
      <ExtraLinks />
    </div>
  );
};

CarDetails.getLayout = (page) => <DefaultLayout>{page}</DefaultLayout>;

export default CarDetails;
